### ISSUE TITLE
IntentReceiver leak exception

### ISSUE THREAD

**Issue by safi-manar** [qtmdev/AndroidInference#20]
**Build:** `1b94548`
**UUID:** `2e24e...`

**Deescription:** This error was attempted to be fixed by putting a try-catch block in `MasterSwitch.startAsynchronous(Context c)` to unregister the receiver. Yet, when the app is force stopped and restarted, the problem persists.

**To Replicate:** 
1. Install a fresh copy of `1b94548`
2. Proceed with the procedure of completing the survey.
3. Once alarms have been set, close the app (double tap and swipe the app to close)
4. Then, Force Stop the app from app info.
5. Restart the app. 
6. Now, close the app as in step 3. The error should occur.
7. At this point, further instances of the error can be replicated by repeating steps 5-6.

**Error:** 

```
06-08 14:24:54.945 3238-3238/us.michaelchen.compasslogger E/ActivityThread: Activity us.michaelchen.compasslogger.MainActivity has leaked IntentReceiver us.michaelchen.compasslogger.receiver.GenericIntentReceiver@f1d90c7 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                            android.app.IntentReceiverLeaked: Activity us.michaelchen.compasslogger.MainActivity has leaked IntentReceiver us.michaelchen.compasslogger.receiver.GenericIntentReceiver@f1d90c7 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
                                                                                at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
                                                                                at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
                                                                                at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
                                                                                at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
                                                                                at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
                                                                                at us.michaelchen.compasslogger.utils.MasterSwitch.startAsynchronous(MasterSwitch.java:149)
                                                                                at us.michaelchen.compasslogger.utils.MasterSwitch.on(MasterSwitch.java:67)
                                                                                at us.michaelchen.compasslogger.MainActivity.collectSurveyFormAndSensorData(MainActivity.java:221)
                                                                                at us.michaelchen.compasslogger.MainActivity.checkPermissions(MainActivity.java:139)
                                                                                at us.michaelchen.compasslogger.MainActivity.onCreate(MainActivity.java:43)
                                                                                at android.app.Activity.performCreate(Activity.java:6251)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by safi-manar** [comment]
This same error coincided with UUID `98166e41`'s data collection buffering at 12:35 (the device awoke from a sleep mode and did not begin sending data, but about half an hour later, all the data since 12:35 was sent in a large batch)

**Comment by safi-manar** [comment]
Persists even after 71503728253accac394dfc644b5f6f50ce700b18 / 3537968d5173acee43c1eeacef82f783a0584bf7
